[project]
authors = ["nitodeco <98180436+nitodeco@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Deep-privacy is a tool for creating privacy reports about online tools"
name = "deep-privacy"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
ui = "streamlit run src/app.py"

[dependencies]
black = ">=25.1.0,<26"
streamlit = ">=1.42.0,<2"
openai = ">=1.61.0,<2"
beautifulsoup4 = ">=4.13.3,<5"
scrapy = ">=2.12.0,<3"
chromadb = ">=0.3.25,<0.4"

[pypi-dependencies]
duckduckgo-search = ">=7.3.2, <8"
