[project]
authors = ["nitodeco <98180436+nitodeco@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Deep-privacy is a tool for creating privacy reports about online tools"
name = "deep-privacy"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
ui = "streamlit run src/app.py"
cli = "python3 src/cli.py"

[dependencies]
black = ">=25.1.0,<26"
streamlit = ">=1.42.0,<2"
openai = ">=1.61.0,<2"
beautifulsoup4 = ">=4.13.3,<5"
chromadb = ">=0.6.3"
pydantic = ">=2.10.6,<3"
python-dotenv = ">=1.0.1,<2"
colorama = ">=0.4.6,<0.5"
requests = ">=2.32.3,<3"

[pypi-dependencies]
duckduckgo-search = ">=7.3.2, <8"
