[server]
headless = true

[client]
showErrorDetails = "none"

[logger]
level = "info"

[theme]
base="light"
primaryColor="#443DFF"
backgroundColor="#F0F2F6"
secondaryBackgroundColor="#FFFFFF"
textColor="#2E3039"
font="sans serif"
